import pandas as pd
df = pd.read_csv("dataset/retail_raw.csv")
print("Dataset Loaded Successfully")
print("\nFirst 5 Rows:")
print(df.head())
print("\n===== DATASET PROFILE =====")
print("\nShape:")
print(df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())
print("\nDuplicate Rows Before Cleaning:")
print(df.duplicated().sum())
print("\n===== CLEANING MISSING VALUES =====")
df["Latitude"] = df["Latitude"].fillna(df["Latitude"].median())
df["Longitude"] = df["Longitude"].fillna(df["Longitude"].median())
df["Footfall"] = df["Footfall"].fillna(df["Footfall"].median())
df["Revenue"] = df["Revenue"].fillna(df["Revenue"].median())
df["Category"] = df["Category"].fillna("Unknown")
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())
print("\n===== REMOVING DUPLICATES =====")
print("Duplicates Before Removal:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates After Removal:", df.duplicated().sum())
print("Dataset Shape After Removing Duplicates:", df.shape)
print("\n===== DATA TRANSFORMATION =====")
df["Date"] = pd.to_datetime(df["Date"])
print("\n===== FEATURE ENGINEERING =====")
df["Revenue_Per_Order"] = df["Revenue"] / df["Orders"]
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df.to_csv("dataset/cleaned_dataset.csv", index=False)
print("\nCleaned Dataset Saved Successfully")
print("\nFinal Shape:")
print(df.shape)
print("\nFirst 5 Rows of Cleaned Dataset:")
print(df.head())